Fix xc7 README
SymbiFlow/symbiflow-examples pull request #100
Opened 2020-12-15 16:21 UTC by rw1nkler

The xc7 README should be removed, since now it is substituted by the sphinx-based documentation.
This change was missing in the initial PR with sphinx support: https://github.com/SymbiFlow/symbiflow-examples/pull/88

2020-12-15 17:20 UTC, rw1nkler commented
It can be seen that the changes appear in the documentation correctly: 
https://symbiflow-examples--100.org.readthedocs.build/en/100/building-examples.html#xilinx-7-series

2020-12-15 17:48 UTC, rw1nkler commented
I opened an issue to add READMEs back to the main toolchain directories (`xc7`, `eos-s3`) - https://github.com/SymbiFlow/symbiflow-examples/issues/101#. 
Nevertheless, I believe that we should merge this PR, because currently the xc7 README is not used by the sphinx documentation.

2020-12-16 17:08 UTC, acomodi requested changes
Comments in

2020-12-16 17:08 UTC, acomodi commented on docs/collect_readmes.py
> +    'zybo': 'Zybo',
```suggestion
    'zybo': 'Zybo Z7',
```

2020-12-17 10:23 UTC, rw1nkler commented on docs/collect_readmes.py
> +    'zybo': 'Zybo',
fixed

2020-12-17 11:48 UTC, acomodi approved these changes
LGTM

2020-12-17 11:50 UTC, tmichalak requested changes
Let's leave the README with some short information where to find the information about building/fetching the toolchain.

2020-12-17 12:06 UTC, rw1nkler commented
Ok, I removed the duplicated information from the README

2020-12-17 13:04 UTC, merged