Timer and Pulse Width modulation examples
SymbiFlow/symbiflow-examples pull request #166
Opened 2021-07-23 23:41 UTC by WhiteNinjaZ

This PR adds two new examples to the documentation. The first is a timer for the basys3 board and the second is a pwm for the multicolored LEDs on the arty. I have also added these designs to the symbiflow-examples.readthedocs.io page. I did this because I felt that it was important to demonstrate to new users that symbiflow can utilize more I/O than just the single colloered LEDs and UART. These designs also demonstrate symbiflows ability to compile SystemVerilog as well as Verilog designs and dictionaries within XDC files.

2021-07-24 02:06 UTC, WhiteNinjaZ commented
@mithro I thought these two designs went together pretty well since one is for arty and one is for basys. I also put the instructions for both in the same document unlike some of my other designs. Let me know if you would like me to split it up further, however, and I will put both designs in separate PRs.

2021-08-06 07:46 UTC, acomodi requested changes
Hi @WhiteNinjaZ, sorry for the delay, and thanks for this PR.

The new designs are not currently being checked in CI. To do so you'd need to add them to the matrix in the CI script like as follows https://github.com/SymbiFlow/symbiflow-examples/blob/5a0200b3eaf7229adb413cf6f34b4ba17e2f2279/.github/workflows/sphinx-tuttest.yml#L25-L32

2021-08-06 07:46 UTC, acomodi commented on xc7/pulse_width_led/PWM.v
> +module PWM(
This has a possibly wrong formatting (as `PWM_top.v`). Maybe worth to run through the verible formatter all the designs.

2021-08-19 10:27 UTC, tmichalak commented
@WhiteNinjaZ please rebase

2021-09-08 14:50 UTC, mkurc-ant commented
@WhiteNinjaZ Please rebase again :) There has been a fix for QuickLogic tests in CI

2021-09-10 03:22 UTC, WhiteNinjaZ commented
@mkurc-ant should be GTG. I have rebased and CI is green.

2021-09-10 08:14 UTC, merged