Common Makefile
SymbiFlow/symbiflow-examples pull request #174
Opened 2021-08-11 00:46 UTC by WhiteNinjaZ

In response to the comments made by @acomodi and @kgugala  in [PR #167](https://github.com/SymbiFlow/symbiflow-examples/pull/167#discussion_r684103579), this PR moves the redundant pieces of the Makefiles throughout symbiflow-examples into a separate common Makefile that each design calls. The way the designs are currently set up, a user should specify the name of their target device (i.e. basys3, arty_35, zybo, etc.), the name of their top level module, their HDL design sources, any memory initialization files, and what constraint files they are using before calling the common Makefile. The common Makefile will take care of setting the various board parameters, as well as running the commands to build the design. I also added error checking for unsupported board types to the common makefile.   
I decided to have the common makefile control the board parameters because I think it makes the example design if/else blocks more clean. This method also makes it simpler for a user to build on the common makefile. Users only need to specify their target board type, HDL design sources, name of top level module, and constraint files in order to build there own designs instead of having to worry about getting the correct part names for their board.

2021-08-11 07:40 UTC, acomodi commented on xc7/counter_test/Makefile
> +
Rather than having other targets, you may `include` the common Makefile which will let you use all its targets as if they were defined here.

2021-08-12 09:16 UTC, acomodi requested changes
LGTM apart from one more minor comment

2021-08-12 09:16 UTC, acomodi commented on common/Makefile
> +  endif
I think that creating symlinks of the mem init files can be avoided. 

I see this is done as the init files are present for the linux litex demo, but I am quite sure that the symlinking step was actually unnecessary.

2021-08-12 21:42 UTC, WhiteNinjaZ commented
Do we also want to incorporate the changes suggested in Issue [#155](https://github.com/SymbiFlow/symbiflow-examples/issues/155) to this PR?

2021-08-16 09:44 UTC, acomodi approved these changes
Changes LGTM, as last step can you please rebase on top of master? Once that's done and CI is green once again I believe we can merge.

2021-08-16 21:05 UTC, WhiteNinjaZ commented
@acomodi Alright just re-based onto master. We should be good now.

2021-08-17 07:39 UTC, acomodi approved these changes
LGTM, merging

2021-08-17 07:39 UTC, merged